# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8ae5470024e0da0ade211fc2033a686e953fcc21a6584d48123a68fdbe5bd9d4d15617e3c0a6af631f1f3f8fc20902f52ebbc28fcfc5952021a37e20a9888a75

test:
  secret_key_base: 5b3a28e428a967578e6993e13550fba7cd17353194225e0d20109e4d5d4bcf17de2e564634fb1c43249b5cde46f315b088c7fc14c739f93e6e984e2a52ec614c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
